export const TARGET_COMPANIES = [
  // === 传统科技巨头 ===
  { value: "google", label: "Google" },
  { value: "microsoft", label: "Microsoft" },
  { value: "amazon", label: "Amazon" },
  { value: "meta", label: "Meta (Facebook)" },
  { value: "apple", label: "Apple" },
  { value: "netflix", label: "Netflix" },
  { value: "uber", label: "Uber" },
  { value: "airbnb", label: "Airbnb" },
  { value: "linkedin", label: "LinkedIn" },
  { value: "twitter", label: "Twitter" },
  { value: "salesforce", label: "Salesforce" },
  { value: "oracle", label: "Oracle" },
  { value: "ibm", label: "IBM" },
  { value: "intel", label: "Intel" },
  { value: "nvidia", label: "NVIDIA" },
  { value: "amd", label: "AMD" },
  { value: "cisco", label: "Cisco" },
  { value: "adobe", label: "Adobe" },
  { value: "spotify", label: "Spotify" },
  { value: "slack", label: "Slack" },
  { value: "zoom", label: "Zoom" },
  { value: "palantir", label: "Palantir" },
  { value: "databricks", label: "Databricks" },
  { value: "snowflake", label: "Snowflake" },
  { value: "mongodb", label: "MongoDB" },
  { value: "elastic", label: "Elastic" },
  { value: "splunk", label: "Splunk" },
  { value: "tableau", label: "Tableau" },
  { value: "alteryx", label: "Alteryx" },

  // === AI/机器学习公司 ===
  { value: "openai", label: "OpenAI" },
  { value: "anthropic", label: "Anthropic" },
  { value: "hugging_face", label: "Hugging Face" },
  { value: "scale_ai", label: "Scale AI" },
  { value: "weights_biases", label: "Weights & Biases" },
  { value: "mlflow", label: "MLflow" },
  { value: "h2o_ai", label: "H2O.ai" },
  { value: "dataiku", label: "Dataiku" },
  { value: "domino_data", label: "Domino Data Lab" },

  // === 金融科技公司 ===
  { value: "stripe", label: "Stripe" },
  { value: "square", label: "Square (Block)" },
  { value: "paypal", label: "PayPal" },
  { value: "robinhood", label: "Robinhood" },
  { value: "coinbase", label: "Coinbase" },
  { value: "venmo", label: "Venmo" },
  { value: "chime", label: "Chime" },
  { value: "affirm", label: "Affirm" },
  { value: "klarna", label: "Klarna" },
  { value: "revolut", label: "Revolut" },
  { value: "wise", label: "Wise (TransferWise)" },

  // === 电商/零售科技 ===
  { value: "shopify", label: "Shopify" },
  { value: "etsy", label: "Etsy" },
  { value: "wayfair", label: "Wayfair" },
  { value: "chewy", label: "Chewy" },
  { value: "mercado_libre", label: "MercadoLibre" },
  { value: "wish", label: "Wish" },
  { value: "pinterest", label: "Pinterest" },

  // === 企业软件/SaaS ===
  { value: "atlassian", label: "Atlassian" },
  { value: "servicenow", label: "ServiceNow" },
  { value: "workday", label: "Workday" },
  { value: "okta", label: "Okta" },
  { value: "crowdstrike", label: "CrowdStrike" },
  { value: "zendesk", label: "Zendesk" },
  { value: "hubspot", label: "HubSpot" },
  { value: "mailchimp", label: "Mailchimp" },
  { value: "canva", label: "Canva" },
  { value: "notion", label: "Notion" },
  { value: "figma", label: "Figma" },
  { value: "linear", label: "Linear" },

  // === 健康科技/生物科技 ===
  { value: "verily", label: "Verily (Google)" },
  { value: "tempus", label: "Tempus" },
  { value: "flatiron_health", label: "Flatiron Health" },
  { value: "guardant_health", label: "Guardant Health" },
  { value: "illumina", label: "Illumina" },
  { value: "moderna", label: "Moderna" },
  { value: "pfizer", label: "Pfizer" },

  // === 汽车/出行科技 ===
  { value: "tesla", label: "Tesla" },
  { value: "waymo", label: "Waymo (Google)" },
  { value: "cruise", label: "Cruise (GM)" },
  { value: "lyft", label: "Lyft" },
  { value: "doordash", label: "DoorDash" },
  { value: "grubhub", label: "Grubhub" },
  { value: "instacart", label: "Instacart" },

  // === 游戏/娱乐科技 ===
  { value: "roblox", label: "Roblox" },
  { value: "unity", label: "Unity" },
  { value: "epic_games", label: "Epic Games" },
  { value: "riot_games", label: "Riot Games" },
  { value: "blizzard", label: "Blizzard Entertainment" },
  { value: "valve", label: "Valve Corporation" },

  // === 云服务/基础设施 ===
  { value: "cloudflare", label: "Cloudflare" },
  { value: "digital_ocean", label: "DigitalOcean" },
  { value: "twilio", label: "Twilio" },
  { value: "sendgrid", label: "SendGrid" },
  { value: "auth0", label: "Auth0" },
  { value: "vercel", label: "Vercel" },
  { value: "netlify", label: "Netlify" },

  // === 咨询/专业服务 ===
  { value: "mckinsey", label: "McKinsey & Company" },
  { value: "bain", label: "Bain & Company" },
  { value: "bcg", label: "Boston Consulting Group" },
  { value: "deloitte", label: "Deloitte" },
  { value: "pwc", label: "PwC" },
  { value: "ey", label: "EY" },
  { value: "kpmg", label: "KPMG" },
  { value: "accenture", label: "Accenture" },

  // === 传统行业数字化 ===
  { value: "ge", label: "General Electric" },
  { value: "boeing", label: "Boeing" },
  { value: "lockheed_martin", label: "Lockheed Martin" },
  { value: "johnson_johnson", label: "Johnson & Johnson" },
  { value: "procter_gamble", label: "Procter & Gamble" },
  { value: "coca_cola", label: "Coca-Cola" },
  { value: "pepsi", label: "PepsiCo" },
  { value: "walmart", label: "Walmart" },
  { value: "target", label: "Target" },
  { value: "home_depot", label: "Home Depot" },

  // === 新兴独角兽公司 ===
  { value: "discord", label: "Discord" },
  { value: "airtable", label: "Airtable" },
  { value: "retool", label: "Retool" },
  { value: "webflow", label: "Webflow" },
  { value: "bubble", label: "Bubble" },

  // === 中国科技公司 ===
  { value: "alibaba", label: "Alibaba" },
  { value: "tencent", label: "Tencent" },
  { value: "bytedance", label: "ByteDance (TikTok)" },
  { value: "baidu", label: "Baidu" },
  { value: "jd", label: "JD.com" },
  { value: "meituan", label: "Meituan" },
  { value: "xiaomi", label: "Xiaomi" },
  { value: "huawei", label: "Huawei" },

  // === 其他选项 ===
  { value: "other", label: "其他" }
];

export const TARGET_INDUSTRIES = [
  { value: "technology", label: "科技/互联网" },
  { value: "finance", label: "金融/银行" },
  { value: "healthcare", label: "医疗/健康" },
  { value: "retail", label: "零售/电商" },
  { value: "manufacturing", label: "制造业" },
  { value: "education", label: "教育" },
  { value: "consulting", label: "咨询" },
  { value: "media", label: "媒体/娱乐" },
  { value: "transportation", label: "交通/物流" },
  { value: "energy", label: "能源/公用事业" },
  { value: "government", label: "政府/非营利" },
  { value: "real_estate", label: "房地产" },
  { value: "agriculture", label: "农业" },
  { value: "tourism", label: "旅游/酒店" },
  { value: "sports", label: "体育" },
  { value: "other", label: "其他" }
];

// 学校列表常量
export const SCHOOLS = [
  { value: "stanford", label: "Stanford University" },
  { value: "mit", label: "MIT" },
  { value: "harvard", label: "Harvard University" },
  { value: "cmu", label: "Carnegie Mellon University" },
  { value: "berkeley", label: "UC Berkeley" },
  { value: "caltech", label: "Caltech" },
  { value: "princeton", label: "Princeton University" },
  { value: "yale", label: "Yale University" },
  { value: "columbia", label: "Columbia University" },
  { value: "upenn", label: "University of Pennsylvania" },
  { value: "cornell", label: "Cornell University" },
  { value: "brown", label: "Brown University" },
  { value: "dartmouth", label: "Dartmouth College" },
  { value: "duke", label: "Duke University" },
  { value: "northwestern", label: "Northwestern University" },
  { value: "jhu", label: "Johns Hopkins University" },
  { value: "rice", label: "Rice University" },
  { value: "vanderbilt", label: "Vanderbilt University" },
  { value: "washu", label: "Washington University in St. Louis" },
  { value: "emory", label: "Emory University" },
  { value: "georgetown", label: "Georgetown University" },
  { value: "nyu", label: "New York University" },
  { value: "usc", label: "University of Southern California" },
  { value: "ucla", label: "UCLA" },
  { value: "ucsd", label: "UC San Diego" },
  { value: "uci", label: "UC Irvine" },
  { value: "ucsb", label: "UC Santa Barbara" },
  { value: "ucdavis", label: "UC Davis" },
  { value: "ucsc", label: "UC Santa Cruz" },
  { value: "ucriverside", label: "UC Riverside" },
  { value: "ucmerced", label: "UC Merced" },
  { value: "gatech", label: "Georgia Institute of Technology" },
  { value: "uiuc", label: "University of Illinois Urbana-Champaign" },
  { value: "umich", label: "University of Michigan" },
  { value: "uwmadison", label: "University of Wisconsin-Madison" },
  { value: "purdue", label: "Purdue University" },
  { value: "osu_ohio", label: "Ohio State University" },
  { value: "psu", label: "Penn State University" },
  { value: "rutgers", label: "Rutgers University" },
  { value: "buffalo", label: "SUNY Buffalo" },
  { value: "stonybrook", label: "SUNY Stony Brook" },
  { value: "binghamton", label: "SUNY Binghamton" },
  { value: "albany", label: "SUNY Albany" },
  { value: "arizona", label: "University of Arizona" },
  { value: "asu", label: "Arizona State University" },
  { value: "ut", label: "University of Texas at Austin" },
  { value: "tamu", label: "Texas A&M University" },
  { value: "baylor", label: "Baylor University" },
  { value: "tcu", label: "Texas Christian University" },
  { value: "smu", label: "Southern Methodist University" },
  { value: "utd", label: "University of Texas at Dallas" },
  { value: "utah", label: "University of Utah" },
  { value: "byu", label: "Brigham Young University" },
  { value: "colorado", label: "University of Colorado Boulder" },
  { value: "colorado_state", label: "Colorado State University" },
  { value: "denver", label: "University of Denver" },
  { value: "oregon", label: "University of Oregon" },
  { value: "osu_oregon", label: "Oregon State University" },
  { value: "washington", label: "University of Washington" },
  { value: "wsu", label: "Washington State University" },
  { value: "alaska", label: "University of Alaska" },
  { value: "hawaii", label: "University of Hawaii" },
  { value: "minnesota", label: "University of Minnesota" },
  { value: "iowa", label: "University of Iowa" },
  { value: "iowa_state", label: "Iowa State University" },
  { value: "nebraska", label: "University of Nebraska" },
  { value: "kansas", label: "University of Kansas" },
  { value: "kansas_state", label: "Kansas State University" },
  { value: "missouri", label: "University of Missouri" },
  { value: "arkansas", label: "University of Arkansas" },
  { value: "oklahoma", label: "University of Oklahoma" },
  { value: "oklahoma_state", label: "Oklahoma State University" },
  { value: "lsu", label: "Louisiana State University" },
  { value: "tulane", label: "Tulane University" },
  { value: "ole_miss", label: "University of Mississippi" },
  { value: "mississippi_state", label: "Mississippi State University" },
  { value: "alabama", label: "University of Alabama" },
  { value: "auburn", label: "Auburn University" },
  { value: "uab", label: "University of Alabama at Birmingham" },
  { value: "uga", label: "University of Georgia" },
  { value: "georgia_tech", label: "Georgia Institute of Technology" },
  { value: "fsu", label: "Florida State University" },
  { value: "uf", label: "University of Florida" },
  { value: "umiami", label: "University of Miami" },
  { value: "usf", label: "University of South Florida" },
  { value: "ucf", label: "University of Central Florida" },
  { value: "fau", label: "Florida Atlantic University" },
  { value: "fiu", label: "Florida International University" },
  { value: "nova", label: "Nova Southeastern University" },
  { value: "custom", label: "自定义填写" },
  { value: "other", label: "其他美国大学" }
];