export const TARGET_COMPANIES = [
  { value: "google", label: "Google" },
  { value: "microsoft", label: "Microsoft" },
  { value: "amazon", label: "Amazon" },
  { value: "meta", label: "Meta (Facebook)" },
  { value: "apple", label: "Apple" },
  { value: "netflix", label: "Netflix" },
  { value: "uber", label: "Uber" },
  { value: "airbnb", label: "Airbnb" },
  { value: "linkedin", label: "LinkedIn" },
  { value: "twitter", label: "Twitter" },
  { value: "salesforce", label: "Salesforce" },
  { value: "oracle", label: "Oracle" },
  { value: "ibm", label: "IBM" },
  { value: "intel", label: "Intel" },
  { value: "nvidia", label: "NVIDIA" },
  { value: "amd", label: "AMD" },
  { value: "cisco", label: "Cisco" },
  { value: "adobe", label: "Adobe" },
  { value: "spotify", label: "Spotify" },
  { value: "slack", label: "Slack" },
  { value: "zoom", label: "Zoom" },
  { value: "palantir", label: "Palantir" },
  { value: "databricks", label: "Databricks" },
  { value: "snowflake", label: "Snowflake" },
  { value: "mongodb", label: "MongoDB" },
  { value: "elastic", label: "Elastic" },
  { value: "splunk", label: "Splunk" },
  { value: "tableau", label: "Tableau" },
  { value: "alteryx", label: "Alteryx" },
  { value: "other", label: "其他" }
];

export const TARGET_INDUSTRIES = [
  { value: "technology", label: "科技/互联网" },
  { value: "finance", label: "金融/银行" },
  { value: "healthcare", label: "医疗健康" },
  { value: "retail", label: "零售/电商" },
  { value: "manufacturing", label: "制造业" },
  { value: "consulting", label: "咨询" },
  { value: "media", label: "媒体/娱乐" },
  { value: "education", label: "教育" },
  { value: "government", label: "政府/公共部门" },
  { value: "nonprofit", label: "非营利组织" },
  { value: "energy", label: "能源" },
  { value: "transportation", label: "交通运输" },
  { value: "real_estate", label: "房地产" },
  { value: "insurance", label: "保险" },
  { value: "telecommunications", label: "电信" },
  { value: "automotive", label: "汽车" },
  { value: "aerospace", label: "航空航天" },
  { value: "pharmaceuticals", label: "制药" },
  { value: "biotechnology", label: "生物技术" },
  { value: "other", label: "其他" }
]; 